# Generated by Django 3.2.3 on 2022-05-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0002_auto_20220503_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletegameevent',
            name='medal',
            field=models.CharField(choices=[('1', 'Gold'), ('2', 'Silver'), ('3', 'Bronze')], max_length=1, null=True),
        ),
    ]
