# Generated by Django 3.2.3 on 2022-05-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0003_alter_athletegameevent_medal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletegame',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
