# Generated by Django 3.2.3 on 2022-05-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0006_rename_code_noc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
