# Generated by Django 3.2.3 on 2022-05-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0007_alter_sport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='athletegame',
            unique_together={('team', 'game', 'athlete')},
        ),
        migrations.AlterUniqueTogether(
            name='athletegameevent',
            unique_together={('athlete_game', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name', 'sport')},
        ),
        migrations.AlterUniqueTogether(
            name='games',
            unique_together={('year', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'noc')},
        ),
    ]
