# Generated by Django 3.2.3 on 2022-05-05 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0008_auto_20220505_1522'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name',)},
        ),
        migrations.RemoveField(
            model_name='team',
            name='noc',
        ),
    ]
