# Generated by Django 3.2.3 on 2022-05-05 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0009_auto_20220505_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='noc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='olympics.noc'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'noc')},
        ),
    ]
